/** A six- or eight-digit hexadecimal color accepted by the native sheet. */
export type HexColor = `#${string}`;

/** Optional visual overrides applied to the native payment sheet. */
export interface PaymentSheetAppearance {
  /** Accent color for primary actions. */
  primaryColor?: HexColor;
  /** Background color for the sheet. */
  backgroundColor?: HexColor;
  /** Primary text color. */
  textColor?: HexColor;
  /** Sheet corner radius in points, from 0 through 40. */
  cornerRadius?: number;
}

/** Optional W3C trace context for correlating application and SDK activity. */
export interface PaymentSheetTelemetry {
  /** Whether native SDK telemetry is enabled. Defaults to `true`. */
  enabled?: boolean;
  /** W3C `traceparent` value propagated to Inttegro requests. */
  traceparent?: string;
  /** W3C `tracestate` value propagated to Inttegro requests. */
  tracestate?: string;
}

/** Configuration stored for the next payment-sheet presentation. */
export interface PaymentSheetConfiguration {
  /** Client-safe ID of an Order finalized by the merchant backend. */
  orderId: string;
  /** Absolute deep link that resumes the application after external steps. */
  returnURL?: string;
  /** Optional native appearance overrides. */
  appearance?: PaymentSheetAppearance;
  /** Optional SDK diagnostics and distributed-trace configuration. */
  telemetry?: PaymentSheetTelemetry;
}

/** Terminal outcome of one native payment-sheet presentation. */
export type PaymentSheetResult =
  | { status: 'completed'; paymentId?: string }
  | { status: 'canceled' }
  | {
      status: 'failed';
      error: { code: string; message: string; declineCode?: string };
    };

/** Application-facing stages in one payment-sheet presentation. */
export type PaymentSheetEventType =
  | 'presented'
  | 'checkoutLoadStarted'
  | 'checkoutLoadSucceeded'
  | 'checkoutLoadFailed'
  | 'paymentAttemptStarted'
  | 'paymentAttemptFailed'
  | 'confirmationRequired'
  | 'authorizationRequired'
  | 'paymentStatusPolling'
  | 'completed'
  | 'canceled'
  | 'failed';

/**
 * A typed lifecycle event for application UI, analytics, and coordination.
 *
 * `paymentAttemptFailed` and `checkoutLoadFailed` are recoverable: the native
 * sheet remains responsible for displaying the failure and offering a retry.
 * Terminal application behavior belongs in the `PaymentSheetResult` returned
 * by `presentPaymentSheet`.
 */
export interface PaymentSheetEvent {
  /** Random identifier shared by events from one sheet presentation. */
  flowId: string;
  /** Monotonically increasing event order within the flow. */
  sequence: number;
  /** Typed lifecycle transition. */
  type: PaymentSheetEventType;
  /** ISO 8601 timestamp generated by the native SDK. */
  timestamp: string;
  /** Bounded failure category when the transition represents a failure. */
  errorType?: string;
}

/** Stable wire names emitted by the native SDK diagnostic stream. */
export type PaymentSheetTelemetryEventName =
  | 'inttegro.payment_sheet.presented'
  | 'inttegro.checkout.load.started'
  | 'inttegro.checkout.load.succeeded'
  | 'inttegro.checkout.load.failed'
  | 'inttegro.payment.attempt.started'
  | 'inttegro.payment.attempt.failed'
  | 'inttegro.payment.confirmation.required'
  | 'inttegro.payment.authorization.required'
  | 'inttegro.payment.status.polling'
  | 'inttegro.payment_sheet.completed'
  | 'inttegro.payment_sheet.canceled'
  | 'inttegro.payment_sheet.failed'
  | 'inttegro.request.prepared'
  | 'inttegro.http.attempt.started'
  | 'inttegro.response.received'
  | 'inttegro.response.decoded'
  | 'inttegro.request.failed';

/** Privacy-safe diagnostic event emitted during a sheet presentation. */
export interface PaymentSheetTelemetryEvent {
  /** Random identifier shared by events from one sheet presentation. */
  flowId: string;
  /** Monotonically increasing event order within the flow. */
  sequence: number;
  /** Stable diagnostic wire name. */
  name: PaymentSheetTelemetryEventName;
  /** ISO 8601 timestamp generated by the native SDK. */
  timestamp: string;
  /** Checkout network operation associated with this event. */
  operation?:
    | 'checkout.lookup'
    | 'checkout.pay'
    | 'checkout.request_confirmation'
    | 'checkout.confirm_payment';
  /** HTTP response status when one was received. */
  httpStatusCode?: number;
  /** Safe request identifier returned by the Inttegro API. */
  requestId?: string;
  /** Bounded failure category without a raw error message. */
  errorType?: string;
}

/** Removable native event subscription. */
export interface PaymentSheetEventSubscription {
  /** Stops delivering events to the listener. */
  remove(): void;
}
